import type { SqlMigration } from "./types.js";

export const chatDurabilityMigration: SqlMigration = {
  id: "0032_chat_durability",
  description: "Persist turn admission identity and canonical transcript projection keys",
  statements: [
    `ALTER TABLE messages ADD COLUMN IF NOT EXISTS canonical_turn_id TEXT`,
    `ALTER TABLE messages ADD COLUMN IF NOT EXISTS canonical_run_attempt_id TEXT`,
    `ALTER TABLE messages ADD COLUMN IF NOT EXISTS canonical_item_id TEXT`,
    `ALTER TABLE messages ADD COLUMN IF NOT EXISTS canonical_phase TEXT`,
    `ALTER TABLE message_parts ADD COLUMN IF NOT EXISTS source_event_id TEXT`,
    `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS thread_binding_source TEXT`,
    `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS current_turn_id TEXT`,
    `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS admission_sequence BIGINT NOT NULL DEFAULT 0`,
    `DO $$ BEGIN IF EXISTS (SELECT 1 FROM sessions WHERE thread_id IS NOT NULL GROUP BY thread_id HAVING COUNT(*) > 1) THEN RAISE EXCEPTION 'duplicate session thread_id values prevent immutable thread ownership'; END IF; END $$`,
    `CREATE UNIQUE INDEX IF NOT EXISTS sessions_thread_id_unique_idx ON sessions (thread_id) WHERE thread_id IS NOT NULL`,
    `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sessions_thread_binding_source_check') THEN ALTER TABLE sessions ADD CONSTRAINT sessions_thread_binding_source_check CHECK (thread_binding_source IS NULL OR thread_binding_source IN ('existing','runtime_admission','legacy_recovery')); END IF; END $$`,
    `CREATE OR REPLACE FUNCTION prevent_thread_id_rebinding() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.thread_id IS NOT NULL AND NEW.thread_id IS DISTINCT FROM OLD.thread_id THEN RAISE EXCEPTION 'session thread_id is immutable'; END IF; RETURN NEW; END $$`,
    `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'sessions_thread_id_immutable') THEN CREATE TRIGGER sessions_thread_id_immutable BEFORE UPDATE OF thread_id ON sessions FOR EACH ROW EXECUTE FUNCTION prevent_thread_id_rebinding(); END IF; END $$`,
    `CREATE UNIQUE INDEX IF NOT EXISTS messages_canonical_item_phase_idx ON messages (session_id, canonical_turn_id, canonical_run_attempt_id, canonical_item_id, canonical_phase) WHERE canonical_turn_id IS NOT NULL AND canonical_run_attempt_id IS NOT NULL AND canonical_item_id IS NOT NULL AND canonical_phase IS NOT NULL`,
    `CREATE UNIQUE INDEX IF NOT EXISTS message_parts_source_event_id_idx ON message_parts (source_event_id) WHERE source_event_id IS NOT NULL`,
    `CREATE TABLE IF NOT EXISTS canonical_turn_admissions (
      session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
      client_message_id TEXT NOT NULL,
      thread_id TEXT NOT NULL,
      turn_id TEXT NOT NULL UNIQUE,
      run_attempt_id TEXT NOT NULL UNIQUE,
      run_id TEXT NOT NULL,
      workspace_id TEXT,
      revision_of_turn_id TEXT,
      admission_order BIGINT,
      admission_state TEXT NOT NULL CHECK (admission_state IN ('reserved', 'admitted')),
      execution_state TEXT NOT NULL DEFAULT 'pending' CHECK (execution_state IN ('pending','running','recovery_required','settled')),
      execution_claim_id TEXT,
      execution_claimed_at TIMESTAMPTZ,
      request_fingerprint TEXT,
      provenance TEXT NOT NULL DEFAULT 'runtime',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      admitted_at TIMESTAMPTZ,
      PRIMARY KEY (session_id, client_message_id)
    )`,
    `CREATE INDEX IF NOT EXISTS canonical_turn_admissions_session_turn_idx ON canonical_turn_admissions (session_id, turn_id)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS canonical_turn_admissions_session_order_idx ON canonical_turn_admissions (session_id, admission_order) WHERE admission_order IS NOT NULL`,
    `CREATE INDEX IF NOT EXISTS canonical_turn_admissions_run_idx ON canonical_turn_admissions (run_id)`,
  ],
};
