export {
  DefaultPlatformClient,
  createPlatformClient,
} from "./platform/client.js";
export {
  PlatformClientContractError,
  PlatformClientOperationError,
  normalizePlatformClientOperationError,
  parsePlatformOperationErrorCode,
  parseProtocolErrorEnvelope,
  type PlatformClientOperationErrorCode,
} from "./platform/errors.js";
export {
  createPlatformHttpTransport,
  type PlatformHttpTransportOptions,
} from "./platform/http-transport.js";
export {
  HookInvocationAuditEventSchema,
  type HookInvocationAuditEvent,
} from "@repo/hook-protocol";
export {
  HookAuditProjectionError,
  applyHookAuditLifecycleEvent,
  buildHookSettingsAuditReadModel,
  createHookAuditProjection,
  projectHookAuditLifecycleEvent,
  replayHookAuditLifecycleEvents,
  type HookAuditProjectionState,
  type HookSettingsAuditReadModel,
} from "./platform/hook-audit-projection.js";
export {
  LifecycleEventSchema,
  type ApprovalId,
  type EventId,
  type EventIdempotencyKey,
  type ItemId,
  type ItemKind,
  type LifecycleEvent,
  type RunAttemptId,
  type ThreadId,
  type TurnDiffPayload,
  type TurnId,
} from "@repo/platform-protocol";
export {
  turnIdFromRunId,
  turnSeedFromLatestUserMessage,
} from "@repo/platform-protocol/lifecycle-turn-routing";
export { followLifecycleEvents } from "./platform/lifecycle-continuation.js";
export {
  LifecycleContinuationError,
  createLifecycleOrderingState,
  type LifecycleContinuationErrorCode,
  type LifecycleOrderingState,
} from "./platform/lifecycle-ordering.js";
export {
  FollowLifecycleRequestSchema,
  GetTurnDiffRequestSchema,
  GetTurnDiffResponseSchema,
  InterruptTurnRequestSchema,
  InterruptTurnResponseSchema,
  CompactTurnRequestSchema,
  CompactTurnResponseSchema,
  ReplayLifecycleEventsRequestSchema,
  ReplayLifecycleEventsResponseSchema,
  StartTurnRequestSchema,
  StartTurnResponseSchema,
  SubmitLifecycleApprovalRequestSchema,
  SubmitUserInputResponseRequestSchema,
  type FollowLifecycleRequest,
  type GetTurnDiffRequest,
  type GetTurnDiffResponse,
  type InterruptTurnRequest,
  type InterruptTurnResponse,
  type CompactTurnRequest,
  type CompactTurnResponse,
  type ReplayLifecycleEventsRequest,
  type ReplayLifecycleEventsResponse,
  type StartTurnRequest,
  type StartTurnResponse,
  type SubmitLifecycleApprovalRequest,
  type SubmitUserInputResponseRequest,
} from "./platform/lifecycle-types.js";
export {
  CreateRunRequestSchema,
  CreateThreadRequestSchema,
  ListArtifactsRequestSchema,
  ListArtifactsResponseSchema,
  ListThreadsRequestSchema,
  ListThreadsResponseSchema,
  ReplayRunEventsRequestSchema,
  ReplayRunEventsResponseSchema,
  SubmitApprovalRequestSchema,
  type CreateRunRequest,
  type CreateThreadRequest,
  type ListArtifactsRequest,
  type ListArtifactsResponse,
  type ListThreadsRequest,
  type ListThreadsResponse,
  type PlatformClient,
  type PlatformClientOperationOptions,
  type PlatformClientTransport,
  type ReplayRunEventsRequest,
  type ReplayRunEventsResponse,
  type SubmitApprovalRequest,
} from "./platform/types.js";
export {
  ProviderClient,
  createProviderClient,
  type ProviderClientTransport,
} from "./providers/client.js";
export {
  createByokHttpTransport,
  type ProviderHttpTransportOptions,
} from "./providers/http-transport.js";
export {
  createByokCloudTransport,
  type ProviderCloudTransportOptions,
} from "./providers/cloud-transport.js";
export {
  ProviderClientContractError,
  ProviderClientOperationError,
  ProviderClientTransitionError,
  isProviderErrorEnvelope,
  isRetryableProviderClientErrorCode,
  normalizeProviderClientOperationError,
  parseProviderOperationErrorCode,
  parseProviderErrorEnvelope,
  type ProviderClientOperationErrorCode,
} from "./providers/errors.js";
export {
  PROVIDER_LIFECYCLE_STEPS,
  createInitialProviderLifecycleState,
  isProviderLifecycleStep,
  transitionProviderLifecycle,
  type ProviderLifecycleTransition,
  type ProviderLifecycleState,
  type ProviderLifecycleStep,
} from "./providers/state-machine.js";
export {
  type ProviderModelsQuery,
  BYOKCredentialSchema,
  BYOKCredentialConnectRequestSchema,
  BYOKCredentialUpdateRequestSchema,
  BYOKCredentialValidateRequestSchema,
  BYOKCredentialValidateResponseSchema,
  BYOKDiscoveredProviderModelsQuerySchema,
  BYOKDiscoveredProviderModelsRefreshResponseSchema,
  BYOKDiscoveredProviderModelsResponseSchema,
  BYOKErrorCodeSchema,
  BYOKErrorEnvelopeSchema,
  BYOKErrorSchema,
  BYOKPreferenceSchema,
  BYOKPreferencesUpdateRequestSchema,
  BYOKResolutionSchema,
  BYOKResolveRequestSchema,
  ProviderRegistryEntrySchema,
  type BYOKCredential,
  type BYOKCredentialConnectRequest,
  type BYOKCredentialUpdateRequest,
  type BYOKCredentialValidateRequest,
  type BYOKCredentialValidateResponse,
  type BYOKDiscoveredProviderModelsQuery,
  type BYOKDiscoveredProviderModelsRefreshResponse,
  type BYOKDiscoveredProviderModelsResponse,
  type BYOKError,
  type BYOKErrorCode,
  type BYOKErrorEnvelope,
  type BYOKPreference,
  type BYOKPreferencesUpdateRequest,
  type BYOKResolution,
  type BYOKResolveRequest,
  type ProviderRegistryEntry,
} from "./providers/types.js";
export {
  createTurnWorkflowProjection,
  applyLifecycleEvent,
  replayTurnWorkflowProjection,
  workflowPhaseLabel,
  type TurnWorkflowProjection,
  type WorkflowItem,
  type WorkflowTerminal,
  type WorkflowTerminalState,
  type WorkflowPhase,
  type WorkflowItemKind,
  type WorkflowItemStatus,
  type WorkflowApproval,
} from "./workflow/turn-workflow-projection.js";
export {
  groupToolActivity,
  buildSegmentTitle,
  type ToolActivitySegment,
} from "./workflow/tool-activity-grouping.js";
