import { MockTask } from './types';

export const MOCK_TASKS: Record<string, MockTask> = {
  'onboarding': {
    id: 'onboarding',
    title: 'Add repository onboarding flow',
    repo: 'LegionCode',
    timeAgo: 'just now',
    duration: '1m 24s',
    userPrompt: 'Add a guided repository onboarding flow. Let users connect GitHub, choose a repository and default branch, and show clear loading and error states before opening the workspace.',
    agentAck: 'I’ll update the onboarding flow to guide users through GitHub connection, repository selection, and default branch setup. I’ll also add loading, empty, and error states before opening the workspace.',
    summary: 'Added the repository connection flow with GitHub OAuth, repository selection, default branch setup, and clearer onboarding states. All checks pass and the changes are ready for review.',
    fileName: 'apps/web/components/repo-picker.tsx',
    changes: { added: 47, removed: 9 },
    messages: [],
    toolSteps: [
      { type: 'explore', text: '3 files' },
      { type: 'read', text: 'apps/web/app/onboarding/page.tsx' },
      { type: 'search', text: 'repository connection flow' },
      { type: 'edit', text: 'apps/web/app/onboarding/page.tsx', added: 84, removed: 12 },
      { type: 'edit', text: 'apps/web/components/repo-picker.tsx', added: 47, removed: 9 },
      { type: 'edit', text: 'apps/web/lib/github.ts', added: 28, removed: 4 },
      { type: 'run', text: 'pnpm vitest run onboarding', status: '24 passed' },
    ],
    filesList: [
      { name: 'apps/web/app/onboarding/page.tsx', added: 84, removed: 12 },
      { name: 'apps/web/components/repo-picker.tsx', added: 47, removed: 9 },
      { name: 'apps/web/lib/github.ts', added: 28, removed: 4 },
    ],
    fileDiffs: {
      'apps/web/components/repo-picker.tsx': [
        { type: 'header', code: '@@ -14,18 +14,27 @@ export function RepositoryPicker() {' },
        { type: 'neutral', lineNum: 14, code: '  const { user, isAuthenticated } = useAuth();' },
        { type: 'neutral', lineNum: 15, code: '  const [branches, setBranches] = useState<string[]>([]);' },
        { type: 'neutral', lineNum: 16, code: '  const [selectedBranch, setSelectedBranch] = useState("main");' },
        { type: 'neutral', lineNum: 17, code: '' },
        { type: 'deletion', lineNum: 18, code: '-  return (' },
        { type: 'deletion', lineNum: 19, code: '-    <Button onClick={connectRepository}>' },
        { type: 'deletion', lineNum: 20, code: '-      Connect repository' },
        { type: 'deletion', lineNum: 21, code: '-    </Button>' },
        { type: 'deletion', lineNum: 22, code: '-  );' },
        { type: 'addition', lineNum: 18, code: '+  return (' },
        { type: 'addition', lineNum: 19, code: '+    <RepositoryPicker' },
        { type: 'addition', lineNum: 20, code: '+      repositories={repositories}' },
        { type: 'addition', lineNum: 21, code: '+      selectedRepository={selectedRepository}' },
        { type: 'addition', lineNum: 22, code: '+      selectedBranch={selectedBranch}' },
        { type: 'addition', lineNum: 23, code: '+      onRepositoryChange={setSelectedRepository}' },
        { type: 'addition', lineNum: 24, code: '+      onBranchChange={setSelectedBranch}' },
        { type: 'addition', lineNum: 25, code: '+    />' },
        { type: 'addition', lineNum: 26, code: '+  );' },
        { type: 'neutral', lineNum: 27, code: '}' },
        { type: 'header', code: '@@ -45,12 +54,26 @@ async function handleConnect(repoId: string) {' },
        { type: 'neutral', lineNum: 54, code: '  setLoading(true);' },
        { type: 'deletion', lineNum: 55, code: '-  const repo = await fetchRepo(repoId);' },
        { type: 'addition', lineNum: 55, code: '+  try {' },
        { type: 'addition', lineNum: 56, code: '+    const repo = await connectGithubRepository(repoId);' },
        { type: 'addition', lineNum: 57, code: '+    const branchList = await fetchBranches(repo.id);' },
        { type: 'addition', lineNum: 58, code: '+    setBranches(branchList);' },
        { type: 'addition', lineNum: 59, code: '+    setSelectedRepository(repo);' },
        { type: 'addition', lineNum: 60, code: '+  } catch (err: any) {' },
        { type: 'addition', lineNum: 61, code: '+    setError(err.message || "OAuth connection failed");' },
        { type: 'addition', lineNum: 62, code: '+  } finally {' },
        { type: 'addition', lineNum: 63, code: '+    setLoading(false);' },
        { type: 'addition', lineNum: 64, code: '+  }' },
        { type: 'neutral', lineNum: 65, code: '}' },
      ],
      'apps/web/app/onboarding/page.tsx': [
        { type: 'header', code: '@@ -1,15 +1,38 @@' },
        { type: 'neutral', lineNum: 1, code: 'import React, { useState } from "react";' },
        { type: 'neutral', lineNum: 2, code: 'import { Header } from "@/components/header";' },
        { type: 'deletion', lineNum: 3, code: '-export default function Onboarding() {' },
        { type: 'deletion', lineNum: 4, code: '-  return <div>Legacy onboarding placeholder</div>;' },
        { type: 'deletion', lineNum: 5, code: '-}' },
        { type: 'addition', lineNum: 3, code: '+import { RepositoryPicker } from "@/components/repo-picker";' },
        { type: 'addition', lineNum: 4, code: '+import { GithubAuthStep } from "@/components/github-auth-step";' },
        { type: 'addition', lineNum: 5, code: '+' },
        { type: 'addition', lineNum: 6, code: '+export default function OnboardingPage() {' },
        { type: 'addition', lineNum: 7, code: '+  const [step, setStep] = useState<"connect" | "select" | "ready">("connect");' },
        { type: 'addition', lineNum: 8, code: '+  const [repo, setRepo] = useState<string | null>(null); font-mono' },
        { type: 'addition', lineNum: 9, code: '+  const [branch, setBranch] = useState("main");' },
        { type: 'addition', lineNum: 10, code: '+' },
        { type: 'addition', lineNum: 11, code: '+  return (' },
        { type: 'addition', lineNum: 12, code: '+    <div className="max-w-4xl mx-auto py-12 px-6 space-y-8">' },
        { type: 'addition', lineNum: 13, code: '+      <Header title="Setup workspace" subtitle="Connect GitHub & configure repository" />' },
        { type: 'addition', lineNum: 14, code: '+      {step === "connect" && <GithubAuthStep onComplete={() => setStep("select")} />}' },
        { type: 'addition', lineNum: 15, code: '+      {step === "select" && (' },
        { type: 'addition', lineNum: 16, code: '+        <RepositoryPicker' },
        { type: 'addition', lineNum: 17, code: '+          selectedRepository={repo}' },
        { type: 'addition', lineNum: 18, code: '+          selectedBranch={branch}' },
        { type: 'addition', lineNum: 19, code: '+          onRepositoryChange={setRepo}' },
        { type: 'addition', lineNum: 20, code: '+          onBranchChange={setBranch}' },
        { type: 'addition', lineNum: 21, code: '+          onConfirm={() => setStep("ready")}' },
        { type: 'addition', lineNum: 22, code: '+        />' },
        { type: 'addition', lineNum: 23, code: '+      )}' },
        { type: 'addition', lineNum: 24, code: '+    </div>' },
        { type: 'addition', lineNum: 25, code: '+  );' },
        { type: 'addition', lineNum: 26, code: '+}' },
      ],
      'apps/web/lib/github.ts': [
        { type: 'header', code: '@@ -1,8 +1,22 @@' },
        { type: 'deletion', lineNum: 1, code: '-export async function fetchRepos() { return []; }' },
        { type: 'addition', lineNum: 1, code: '+import { Octokit } from "@octokit/rest";' },
        { type: 'addition', lineNum: 2, code: '+' },
        { type: 'addition', lineNum: 3, code: '+export interface GithubRepo {' },
        { type: 'addition', lineNum: 4, code: '+  id: string;' },
        { type: 'addition', lineNum: 5, code: '+  name: string;' },
        { type: 'addition', lineNum: 6, code: '+  defaultBranch: string;' },
        { type: 'addition', lineNum: 7, code: '+  isPrivate: boolean;' },
        { type: 'addition', lineNum: 8, code: '+}' },
        { type: 'addition', lineNum: 9, code: '+' },
        { type: 'addition', lineNum: 10, code: '+export async function connectGithubRepository(repoId: string): Promise<GithubRepo> {' },
        { type: 'addition', lineNum: 11, code: '+  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });' },
        { type: 'addition', lineNum: 12, code: '+  const [owner, name] = repoId.split("/");' },
        { type: 'addition', lineNum: 13, code: '+  const { data } = await octokit.repos.get({ owner, repo: name });' },
        { type: 'addition', lineNum: 14, code: '+  return {' },
        { type: 'addition', lineNum: 15, code: '+    id: data.full_name,' },
        { type: 'addition', lineNum: 16, code: '+    name: data.name,' },
        { type: 'addition', lineNum: 17, code: '+    defaultBranch: data.default_branch,' },
        { type: 'addition', lineNum: 18, code: '+    isPrivate: data.private,' },
        { type: 'addition', lineNum: 19, code: '+  };' },
        { type: 'addition', lineNum: 20, code: '+}' },
      ],
    },
  },
  'execution': {
    id: 'execution',
    title: 'Polish sandbox execution',
    repo: 'LegionCode',
    timeAgo: '15m ago',
    duration: '8m 12s',
    userPrompt: 'Harden cloud worker sandbox runtimes with boundary checks and status verification endpoints.',
    agentAck: 'I will update the sandbox API worker to include health checks and local runtime verification.',
    summary: 'Orchestrated Sandboxed runtime sessions and local verification curl interfaces. Added baseline validation checks to verify local runtime fingerprints prior to handling execution requests.',
    fileName: 'apps/secure-agent-api/src/index.ts',
    changes: { added: 14, removed: 2 },
    toolSteps: [
      { type: 'explore', text: '2 files' },
      { type: 'read', text: 'apps/secure-agent-api/src/index.ts' },
      { type: 'search', text: 'cloud worker sandbox runtimes' },
      { type: 'edit', text: 'apps/secure-agent-api/src/index.ts', added: 14, removed: 2 },
      { type: 'edit', text: 'apps/secure-agent-api/src/sandbox.ts', added: 32, removed: 8 },
      { type: 'run', text: 'curl -s http://localhost:3000/api/debug/runtime', status: '200 OK' },
    ],
    filesList: [
      { name: 'apps/secure-agent-api/src/index.ts', added: 14, removed: 2 },
      { name: 'apps/secure-agent-api/src/sandbox.ts', added: 32, removed: 8 },
    ],
    fileDiffs: {
      'apps/secure-agent-api/src/index.ts': [
        { type: 'header', code: '@@ -42,12 +42,17 @@ export default {' },
        { type: 'neutral', lineNum: 42, code: 'export default {' },
        { type: 'neutral', lineNum: 43, code: '  async fetch(request, env) {' },
        { type: 'deletion', lineNum: 44, code: '-     return new Response("OK");' },
        { type: 'addition', lineNum: 45, code: '+     const url = new URL(request.url);' },
        { type: 'addition', lineNum: 46, code: '+     if (url.pathname === "/api/debug/runtime") {' },
        { type: 'addition', lineNum: 47, code: '+       return Response.json({' },
        { type: 'addition', lineNum: 48, code: '+         status: "healthy",' },
        { type: 'addition', lineNum: 49, code: '+         runtime: "cloudflare-worker",' },
        { type: 'addition', lineNum: 50, code: '+       });' },
        { type: 'addition', lineNum: 51, code: '+     }' },
        { type: 'neutral', lineNum: 52, code: '     return handleNextRouting(request, env);' },
      ],
      'apps/secure-agent-api/src/sandbox.ts': [
        { type: 'header', code: '@@ -10,8 +10,14 @@' },
        { type: 'neutral', lineNum: 10, code: 'export async function initSandboxSession(sessionId: string) {' },
        { type: 'addition', lineNum: 11, code: '+  const sandbox = await createContainerInstance(sessionId);' },
        { type: 'addition', lineNum: 12, code: '+  await sandbox.verifyFingerprint();' },
        { type: 'addition', lineNum: 13, code: '+  return sandbox;' },
        { type: 'neutral', lineNum: 14, code: '}' },
      ],
    },
  },
  'readme': {
    id: 'readme',
    title: 'Sync README.md docs',
    repo: 'project-alpha',
    timeAgo: '1h ago',
    duration: '4m 30s',
    userPrompt: 'Update architecture documentation and setup prerequisites for local alpha testing.',
    agentAck: 'I will update README.md and setup guides with new launch posture details.',
    summary: 'Updated architecture layout blocks, launch postures, check:boundaries instructions, and prerequisites for local verification workspaces.',
    fileName: 'README.md',
    changes: { added: 45, removed: 5 },
    toolSteps: [
      { type: 'explore', text: '2 files' },
      { type: 'read', text: 'README.md' },
      { type: 'search', text: 'architecture documentation and setup prerequisites' },
      { type: 'edit', text: 'README.md', added: 45, removed: 5 },
      { type: 'edit', text: 'docs/architecture.md', added: 80, removed: 5 },
      { type: 'run', text: 'pnpm check:docs', status: 'verified' },
    ],
    filesList: [
      { name: 'README.md', added: 45, removed: 5 },
      { name: 'docs/architecture.md', added: 80, removed: 5 },
    ],
    fileDiffs: {
      'README.md': [
        { type: 'header', code: '@@ -1,6 +1,8 @@' },
        { type: 'neutral', lineNum: 1, code: '# LegionCode' },
        { type: 'deletion', lineNum: 2, code: '- Local console playground' },
        { type: 'addition', lineNum: 3, code: '+ A multi-agent coding workspace built on isolated execution sandboxes.' },
        { type: 'addition', lineNum: 4, code: '+' },
        { type: 'addition', lineNum: 5, code: '+ ## Launch Posture' },
        { type: 'addition', lineNum: 6, code: '+ LegionCode is currently in **Private Alpha**.' },
      ],
      'docs/architecture.md': [
        { type: 'header', code: '@@ -1,5 +1,9 @@' },
        { type: 'neutral', lineNum: 1, code: '# Architecture Overview' },
        { type: 'addition', lineNum: 2, code: '+ Multi-agent orchestrations run in parallel containers with automated git worktree isolation.' },
      ],
    },
  },
  'verification': {
    id: 'verification',
    title: 'Run validation gates',
    repo: 'project-alpha',
    timeAgo: '3h ago',
    duration: '22s',
    userPrompt: 'Add boundary verification scripts and type check triggers to package.json.',
    agentAck: 'I will add check:boundaries and check-types npm scripts to package.json.',
    summary: 'Added validation scripts for package boundaries and type checks so workspace contracts stay consistent across apps.',
    fileName: 'package.json',
    changes: { added: 3, removed: 0 },
    toolSteps: [
      { type: 'explore', text: '2 files' },
      { type: 'read', text: 'package.json' },
      { type: 'search', text: 'boundary verification scripts' },
      { type: 'edit', text: 'package.json', added: 3, removed: 0 },
      { type: 'edit', text: '.dependency-cruiser.json', added: 15, removed: 2 },
      { type: 'run', text: 'pnpm check:boundaries', status: '0 violations' },
    ],
    filesList: [
      { name: 'package.json', added: 3, removed: 0 },
      { name: '.dependency-cruiser.json', added: 15, removed: 2 },
    ],
    fileDiffs: {
      'package.json': [
        { type: 'header', code: '@@ -12,4 +12,7 @@' },
        { type: 'neutral', lineNum: 12, code: '  "scripts": {' },
        { type: 'addition', lineNum: 13, code: '    "check:boundaries": "dependency-cruiser --config .dependency-cruiser.json apps packages",' },
        { type: 'addition', lineNum: 14, code: '    "check-types": "pnpm --recursive exec tsc --noEmit",' },
        { type: 'neutral', lineNum: 15, code: '    "lint": "eslint ."' },
      ],
      '.dependency-cruiser.json': [
        { type: 'header', code: '@@ -1,5 +1,10 @@' },
        { type: 'neutral', lineNum: 1, code: '{' },
        { type: 'addition', lineNum: 2, code: '  "forbidden": [{ "name": "no-circular-deps", "severity": "error" }]' },
        { type: 'neutral', lineNum: 3, code: '}' },
      ],
    },
  },
};
